# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  # import Cypress orb by specifying an exact version x.y.z
  # or the latest version 1.x.x using "@1" syntax
  cypress: cypress-io/cypress@1
  node: circleci/node@1.1.6
workflows:
  build:
    executor:
      name: node/default
    jobs:
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test:unit
      - cypress/run:
          start: npm run serve
          wait-on: 'http://localhost:8080'
